language: cpp
sudo: false
matrix:
  include:
  - env: QT_VERSION=qt5
    os: linux
    dist: xenial # Ubuntu 16.04 LTS
    compiler: gcc
    addons:
      apt:
        packages:
          - build-essential
          - qt5-default
          - qt5-qmake
          - qtbase5-dev-tools
          - qtmultimedia5-dev
  - env: QT_VERSION=qt5
    os: linux
    compiler: clang
    dist: xenial # Ubuntu 16.04 LTS
    addons:
      apt:
        packages:
          - qt5-default
          - qt5-qmake
          - qtbase5-dev-tools
          - qtmultimedia5-dev
  - env: QT_VERSION=qt5
    os: osx
    osx_image: xcode9.2
    compiler: gcc
  - env: QT_VERSION=qt5
    os: osx
    osx_image: xcode9.2
    compiler: clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update -all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt; fi
script: ./qt_make.sh

